services:
    oai-flexric:
        image: ${REGISTRY:-oaisoftwarealliance}/oai-flexric:${FLEXRIC_TAG:-develop}
        container_name: oai-flexric
        networks:
            public_net:
                ipv4_address: 192.168.70.155
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf
            - sharedXappLibs:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nearRT-RIC"
            interval: 10s
            timeout: 5s

