services:
    oai-flexric:
        image: ${REGISTRY:-oaisoftwarealliance}/oai-flexric:${FLEXRIC_TAG:-develop}
        container_name: oai-flexric
        privileged: true
        networks:
           rfsim5g-oai-public-net:
                ipv4_address: 192.168.71.155
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf
            - sharedXappLibs:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nearRT-RIC"
            interval: 10s
            timeout: 5s

networks:
  rfsim5g-oai-public-net:
    name: rfsim5g-oai-public-net
    external: true
  rfsim5g-oai-traffic-net:
    name: rfsim5g-oai-traffic-net
    external: true

volumes:
  sharedXappLibs:
