services:
  oai-gnb-cu:
    container_name: oai-gnb-cu
    image: oai-gnb
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gnb-cu.conf:/opt/oai-gnb/etc/gnb.conf
      - ../flexric/flexric/:/usr/local/lib/flexric/
    depends_on:
      - oai-gnb-du
    command: >
      /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf --sa
    networks:
      rfsim5g-oai-core-net:
        ipv4_address: 192.168.71.140

  oai-gnb-du:
    container_name: oai-gnb-du
    image: oai-gnb
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gnb-du.conf:/opt/oai-gnb/etc/gnb.conf
      - ../flexric/flexric/:/usr/local/lib/flexric/
    command: >
      /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf -E --rfsim --log_config.global_log_options level,nocolor,time --MACRLCs.[0].local_n_address 192.168.72.3 --MACRLCs.[0].remote_n_address oai-cucp --MACRLCs.[0].local_n_address_f1u 192.168.73.3
    networks:
      rfsim5g-oai-core-net:
        ipv4_address: 192.168.71.141

networks:
  rfsim5g-oai-core-net:
    name: rfsim5g-oai-core-net
    external: true
  rfsim5g-oai-traffic-net:
    name: rfsim5g-oai-traffic-net
    external: true
  rfsim5g-oai-f1c-net:
    name: rfsim5g-oai-f1c-net
    external: true
  rfsim5g-oai-f1u-1-net:
    name: rfsim5g-oai-f1u-1-net
    external: true
  rfsim5g-oai-f1u-2-net:
    name: rfsim5g-oai-f1u-2-net
    external: true
  rfsim5g-oai-f1u-3-net:
    name: rfsim5g-oai-f1u-3-net
    external: true
  rfsim5g-oai-e1-net:
    name: rfsim5g-oai-e1-net
    external: true
  rfsim5g-oai-ue-net:
    name: rfsim5g-oai-ue-net
    external: true
  rfsim5g-oai-e2-net:
    name: rfsim5g-oai-e2-net
    external: true


