version: '3.8'

services:
  oai-gnb:
    container_name: oai-gnb
    image: oai-gnb
    restart: unless-stopped
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gnb.conf:/opt/oai-gnb/etc/gnb.conf
      - ../flexric/flexric/:/usr/local/lib/flexric/
    command: >
      -O /opt/oai-gnb/etc/gnb.conf -E --rfsim --log_config.global_log_options level,nocolor,time
    healthcheck:
      test: /bin/bash -c "pgrep nr-softmodem"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: 192.168.71.140

networks:
    rfsim5g-oai-public-net:
        name: rfsim5g-oai-public-net
        external: true
    rfsim5g-oai-traffic-net:
        name: rfsim5g-oai-traffic-net
        external: true
