services:
  oai-gnb-cu:
    container_name: oai-gnb-cu
    image: oai-gnb
    privileged: true
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gnb-cu.conf:/opt/oai-gnb/etc/gnb.conf
      - ../flexric/flexric/:/usr/local/lib/flexric/
    depends_on:
      - oai-gnb-du
    command: >
      /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf --sa
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: 192.168.71.140

  oai-gnb-du:
    container_name: oai-gnb-du
    image: oai-gnb
    privileged: true
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gnb-du.conf:/opt/oai-gnb/etc/gnb.conf
      - ../flexric/flexric/:/usr/local/lib/flexric/
    command: >
      /opt/oai-gnb/bin/nr-softmodem -O /opt/oai-gnb/etc/gnb.conf --rfsim --sa -E
    networks:
      rfsim5g-oai-public-net:
        ipv4_address: 192.168.71.141

networks:
  rfsim5g-oai-public-net:
    name: rfsim5g-oai-public-net
    external: true
  rfsim5g-oai-traffic-net:
    name: rfsim5g-oai-traffic-net
    external: true

