services:
    oai-nr-ue:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRUE_IMG:-oai-nr-ue}:${TAG:-develop}
        container_name: rfsim5g-oai-nr-ue
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3600000000 --band 78
                                    --uicc0.imsi 208990100001100 --uicc0.nssai_sst 1
                                    --rfsimulator.serveraddr 192.168.78.2
        networks:
            rfsim5g-oai-ue-net:
                ipv4_address: 192.168.78.5
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue2:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRUE_IMG:-oai-nr-ue}:${TAG:-develop}
        container_name: rfsim5g-oai-nr-ue2
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3619200000
                                    --uicc0.imsi 208990100001101 --uicc0.nssai_sst 2
                                    --rfsimulator.serveraddr 192.168.78.3
        networks:
            rfsim5g-oai-ue-net:
                ipv4_address: 192.168.78.6
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue3:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRUE_IMG:-oai-nr-ue}:${TAG:-develop}
        container_name: rfsim5g-oai-nr-ue3
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3619200000
                                    --uicc0.imsi 208990100001102 --uicc0.nssai_sst 3
                                    --rfsimulator.serveraddr 192.168.78.4
            ASAN_OPTIONS: detect_leaks=0
        networks:
            rfsim5g-oai-ue-net:
                ipv4_address: 192.168.78.7
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    rfsim5g-oai-core-net:
      external: true
      name: rfsim5g-oai-core-net
    rfsim5g-oai-traffic-net:
      external: true
      name: rfsim5g-oai-traffic-net
    rfsim5g-oai-f1c-net:
      external: true
      name: rfsim5g-oai-f1c-net
    rfsim5g-oai-f1u-1-net:
      external: true
      name: rfsim5g-oai-f1u-1-net
    rfsim5g-oai-f1u-2-net:
      external: true
      name: rfsim5g-oai-f1u-2-net
    rfsim5g-oai-f1u-3-net:
      external: true
      name: rfsim5g-oai-f1u-3-net
    rfsim5g-oai-e1-net:
      external: true
      name: rfsim5g-oai-e1-net
    rfsim5g-oai-ue-net:
      external: true
      name: rfsim5g-oai-ue-net
    rfsim5g-oai-e2-net:
      external: true
      name: rfsim5g-oai-e2-net


