services:
    oai-flexric:
        image: ${REGISTRY:-oaisoftwarealliance}/oai-flexric:${FLEXRIC_TAG:-develop}
        container_name: oai-flexric
        networks:
            rfsim5g-oai-e2-net:
                ipv4_address: 192.168.70.150
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf
            - sharedXappLibs:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nearRT-RIC"
            interval: 10s
            timeout: 5s

volumes:
    sharedXappLibs:

networks:
    rfsim5g-oai-core-net:
      external: true
      name: rfsim5g-oai-core-net
    rfsim5g-oai-traffic-net:
      external: true
      name: rfsim5g-oai-traffic-net
    rfsim5g-oai-f1c-net:
      external: true
      name: rfsim5g-oai-f1c-net
    rfsim5g-oai-f1u-1-net:
      external: true
      name: rfsim5g-oai-f1u-1-net
    rfsim5g-oai-f1u-2-net:
      external: true
      name: rfsim5g-oai-f1u-2-net
    rfsim5g-oai-f1u-3-net:
      external: true
      name: rfsim5g-oai-f1u-3-net
    rfsim5g-oai-e1-net:
      external: true
      name: rfsim5g-oai-e1-net
    rfsim5g-oai-ue-net:
      external: true
      name: rfsim5g-oai-ue-net
    rfsim5g-oai-e2-net:
      external: true
      name: rfsim5g-oai-e2-net

