services:
    oai-cucp:
        image: oai-cucp:flexric
        container_name: rfsim5g-oai-cucp
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.77.2
                                    --gNBs.[0].local_s_address 192.168.72.2
            ASAN_OPTIONS: detect_leaks=0
        networks:
            rfsim5g-oai-core-net:
                ipv4_address: 192.168.71.150
            rfsim5g-oai-f1c-net:
                ipv4_address: 192.168.72.2
            rfsim5g-oai-e1-net:
                ipv4_address: 192.168.77.2
            rfsim5g-oai-e2-net:
                ipv4_address: 192.168.70.2
        volumes:
            - ../../conf_files/gnb-cucp.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
            - ./libs/:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-cuup:
        image: oai-cuup:flexric
        container_name: rfsim5g-oai-cuup
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.77.2
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cuup 192.168.77.3
                                    --gNBs.[0].local_s_address 192.168.73.2
                                    --gNBs.[0].remote_s_address 127.0.0.1
            ASAN_OPTIONS: detect_leaks=0
        networks:
            rfsim5g-oai-core-net:
                ipv4_address: 192.168.71.161
            rfsim5g-oai-f1u-1-net:
                ipv4_address: 192.168.73.2
            rfsim5g-oai-e1-net:
                ipv4_address: 192.168.77.3
            rfsim5g-oai-e2-net:
                ipv4_address: 192.168.70.3
        volumes:
            - ../../conf_files/gnb-cuup.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
            - ./libs/:/usr/local/lib/flexric/ 
        healthcheck:
            test: /bin/bash -c "pgrep nr-cuup"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-du1: 
        image: oai-du:flexric
        container_name: rfsim5g-oai-du1 
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,time
                                    --gNBs.[0].gNB_ID 0xe10
                                    --rfsimulator.options chanmod
                                    --gNBs.[0].gNB_DU_ID 0xe10                       
                                    --MACRLCs.[0].local_n_address 192.168.72.4      
                                    --MACRLCs.[0].remote_n_address 192.168.72.2 
                                    --MACRLCs.[0].local_n_address_f1u 192.168.73.3  
            ASAN_OPTIONS: detect_leaks=0
        networks:
            rfsim5g-oai-f1c-net:
                ipv4_address: 192.168.72.4
            rfsim5g-oai-f1u-1-net:
                ipv4_address: 192.168.73.3
            rfsim5g-oai-ue-net:
                ipv4_address: 192.168.78.10
            rfsim5g-oai-e2-net:
                ipv4_address: 192.168.70.13
        ports:
          - "2021:2021/tcp"
        volumes:
            - ../../conf_files/gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
            - ./libs/:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-du2:  
        image: oai-du:flexric
        container_name: rfsim5g-oai-du2  
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,time
                                    --gNBs.[0].gNB_ID 0xe20
                                    --rfsimulator.options chanmod
                                    --gNBs.[0].gNB_DU_ID 0xe20
                                    --gNBs.[0].nr_cellid 1
                                    --gNBs.[0].servingCellConfigCommon.[0].physCellId 1
                                    --MACRLCs.[0].local_n_address 192.168.72.5            
                                    --MACRLCs.[0].remote_n_address 192.168.72.2           
                                    --MACRLCs.[0].local_n_address_f1u 192.168.73.4
            ASAN_OPTIONS: detect_leaks=0
        networks:
            rfsim5g-oai-f1c-net:
                ipv4_address: 192.168.72.5 
            rfsim5g-oai-f1u-1-net:
                ipv4_address: 192.168.73.4 
            rfsim5g-oai-ue-net:
                ipv4_address: 192.168.78.20 
            rfsim5g-oai-e2-net:
                ipv4_address: 192.168.70.14 
        ports:
          - "2022:2022/tcp"
        volumes:
            - ../../conf_files/gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
            - ./libs/:/usr/local/lib/flexric/
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    rfsim5g-oai-core-net:
      external: true
      name: rfsim5g-oai-core-net
    rfsim5g-oai-traffic-net:
      external: true
      name: rfsim5g-oai-traffic-net
    rfsim5g-oai-f1c-net:
      external: true
      name: rfsim5g-oai-f1c-net
    rfsim5g-oai-f1u-1-net:
      external: true
      name: rfsim5g-oai-f1u-1-net
    rfsim5g-oai-e1-net:
      external: true
      name: rfsim5g-oai-e1-net
    rfsim5g-oai-ue-net:
      external: true
      name: rfsim5g-oai-ue-net
    rfsim5g-oai-e2-net:
      external: true
      name: rfsim5g-oai-e2-net



